### ISSUE TITLE
databse get error for "Person" table and "person" table

### ISSUE THREAD

**Issue by Mert-Zengin** [Frave07/Flutter-Delivery-App#2]
{
  "resp": false,
  "msg": {
    "code": "ER_NO_SUCH_TABLE",
    "errno": 1146,
    "sqlMessage": "Table 'frave_food.person' doesn't exist", //here
    "sqlState": "42S02",
    "index": 0,
    "sql": "CALL SP_LOGIN('test@gmail.com');"
  }
}

**Comment by Frave07** [comment]
create the database well
